version: '3.2'
services:
  shoppingify_server:
    container_name: 'shoppingify_server_${NODE_ENV}'
    image: 'shoppingify_server_${NODE_ENV}'
    environment:
      - NODE_ENV:${NODE_ENV}
      - PORT:${PORT}
    build:
      context: .
      dockerfile: Dockerfile
      target: '${NODE_ENV}'
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    depends_on:
      - database
    command: ['sh', './wait-for-postgres.sh', 'npm', 'run', 'start:${NODE_ENV}']
    networks:
      - shoppingify
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  database:
    env_file:
      - .env
    container_name: 'shoppingify_database_${NODE_ENV}'
    image: postgres:alpine
    networks:
      - shoppingify
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: '${DB_NAME}'
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
networks:
  shoppingify:
